; generated by SuperSlicer 2.4 on 2023-04-03 at 13:02:17 UTC


;
; thumbnail begin 48x48 500
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAABPUlEQVR4Ae2XP2oCQRTGH5KErMH82Z
; AsxhA2QVuxE8FiWxsNtjZrKwjbWcbWasEL5AgewSPsETyCR1C/QlhEEGdnRtTvB187+7335u28J0II
; IYQQQpS5L5eD4nA4V1GhXg/llLx2u/HPdLrKorde7z/nOM9ik7tSqfY1Hi+ymt/qczRKHqrVX7HBUx
; BEuoyn5U8mS5xtrBo4GPfWhPm08I0b1/VFJ2g208b3VUN0gCazaX63Gpmu1Eur9Xcq81vhTyeqMAAG
; wAAYAAO47gBMDW7HCEkUVfCMIwPfcXx+2U+DrUvn/H9IGOY2+0EoOkE1vH5/Ztp8cTBIcvm8L6YoNB
; oRMmTC/GOzqWeEPgRWyo8oSnQZx0p563k1sQmulNvpxFmr4bbbehpVFTT4exjOVORUKnYWeUIIIYSQ
; C2UNc4SyyoxcUvEAAAAASUVORK5CYII=
; thumbnail end
;

;
; thumbnail begin 300x300 2472
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAHBUlEQVR4Ae3cX2pVZxfA4d1WU01bTJ
; Om/onapIggiga8EK8MXojeSJCAiAgRvQqIXigqKFVBUAQDTsAhOASH4BAcgkNIfQUtatW4cnLWfvd+
; HvhNoJ6zvpP17bWbBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYut+OHFnU4Ptx8+axBhiM
; kamp2d337r3++9mzFQ2+6ceP3/xy8OB8A6zN76dO/VPTl7/moTVx5syyX1sQUH5V7bx581VNX/ouVP
; 6bl//2DbA6W+bmrtX0Je9a5ddW+TdogC8rf45Mnj//vKYvd5fbfuXKyw3j49MN8DGL9XZmIQ+fKMve
; mr7EfcxCnt6zWK8rC3l6y2K9zt4v5P3aohfKB33r5csvavqS6vMs5Om8srwt/wtd0xdTX678W5bTng
; a6xuMK3a382/oTkU7wuEI/Kgt5jz9QNXeA/cpCniqVZazHFfqbhTzVKEvYmr5cWp/cI9J6Fuv6tPJr
; y5+ItIrFur6We0Rawx2gVpt7RNK4A1Qk94gMnTtArSWPPzAU7gA1yDz+wLrZtGfPnDtADTr3iAycxb
; rWO/eIrJnHFTTM3CMSZrGujCzk+S7lg1KWoTV9yNW9LOT5JneAalPuEfkid4Bqa+4R+cBiXTXkHhEv
; 2FN1uUfsIXeAqjn3iD3icQV1IQv5jnMHqC7m8YcOcgeoLmch3yHuANWXLOQrZrGuPmYhXyGLdfU594
; iVcAco/ZeFfIu5A5Q+zwsCW8gdoPT1vCCwBdwBSqvPCwITlWeravqwSG3IM1tJ/D+BUqxy9N8wXAaW
; FMvASmBgSbEMrAQGlhTLwEpgYEmxDKwEBpYUy8BKYGBJsQysBAaWFMvASmBgSbEMrAQGlhTLwEpgYE
; mxDKwEBpYUy8BKYGBJsQysBAaWFMvASmBgSbEMrAQGlhTLwEpgYEmxDKwEBpYUy8BKYGBJsQysBAaW
; FMvASmBgSbEMrAQGlhTLwEpgYEmxDKwEBpYUy8BKYGBJsQysBAaWFMvASmBgSbEMrAQGlhTLwEpgYE
; mxDKwEBpYUy8BKYGBJsQysBAaWFMvASmBgSbEMrAQGlhTLwEpgYEmxDKwEBpYUy8BKYGBJsQysBAaW
; FMvASmBgSbEMrAQGlhTLwEpgYEmxDKwEBpYUy8BKYGBJsQysBAaWFMvASmBgSbEMrAQGlhTLwEpgYE
; mxDKwEBpYUy8BKYGBJsQysBAaWFMvASmBgSbEMrAQGlhTLwEpgYEmxDKwEBpYUy8BKYGBJsQysBAaW
; FMvASmBgSbEMrAQGlhTLwEpgYEmxDKwEBpYUy8BKMLpv3+KuO3fe1PRBkbL76+HDlU0zM/MNw7dxcn
; J266VLr2aWl6v60EgZbb148dVPW7bMNuT5YWRkbMvx48vTjx5V9eGRhlX5VfXb0aPLDe0xMjU1t+Pq
; 1dc1fZCk9e7td+LNyLZt/gRso/Jr6/eTJ59PP3lS1YdKGnQzT5+uTCwsvPxh48axhnbbvHevhbx6W/
; kTcHT//msN9dgwPj77x9mzLyzk1af+vHDh1Y+jo9MN9Xm3kD92bHn3gwd+banTWax3yPuFvF9b6mJl
; sb5hYmKuoTs+PP5gIa+OVBbrYydOPG/orvJra+ft2/5EVNXtvn+/PLG+2NB95dfWHwsLFvKqMov1nv
; r18OFrHn9QLZXF+i+HDjlc7rNyj7h9ack9olqdO0A+sJBXW5t+/NjjCvw/94hqU1PXr7/5edeuxQa+
; pPzaGj992kJeqU2eO2exzuqNHjhgIa+h5w6QsHKP6AWBGlblcQWLddbEPaLWO3eADJx7RK1HXrDHuv
; GCQA2qcgc4Pj/vBXusv/KCQPeIilbuAN9+hizWGZ53Lwh0j6jvzB0gad4v5D3+oG/lDpDWsJDX19q+
; tPTa4wq0intEfVpZrL/9THjBHu1Vfm1N3bjhT8Set/PWrRV3gFTBPWK/cwdIldwj9it3gFTPPWI/8o
; I9OsM9YndzB0hneUFgt3IHSOe5R6y/8rjCxMKCO0D6o9wjWsjXl8U6vfXuHvHsWY8/VJI7QHrPQr79
; WazDJ9wjtrOyWN8wMTHXAB9zj9ieymJ97MQJd4DwLeXXlhcE5rXr7t2VTTMziw2wOuXXlhcEDj93gL
; AGvx4+7B5xCHnBHgzIxsnJ2e1LS+/uEctuRYPNHSAMWPkT8e1ua35kxw4NuAYAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAIbtXxuH+pQbjPkmAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.52mm
; perimeters extrusion width = 0.46mm
; infill extrusion width = 0.60mm
; solid infill extrusion width = 0.48mm
; top infill extrusion width = 0.52mm
; first layer extrusion width = 0.70mm

; object:{"name":"First_Layer_Test","id":"First_Layer_Test.stl id:0 copy 0","object_center":[90.000000,90.000000,0.000000],"boundingbox_center":[90.000000,90.000000,0.100000],"boundingbox_size":[75.000000,75.000000,0.200000]}
; plater:{"center":[90.000000,90.000000,0.000000],"boundingbox_center":[90.000000,90.000000,0.100000],"boundingbox_size":[75.000000,75.000000,0.200000]}

;TYPE:Custom
; custom gcode: start_gcode
print_start EXTRUDER=260 BED=110 CHAMBER_TARGET=0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; custom gcode end: start_gcode
; custom gcode: start_filament_gcode
; Filament gcode
; custom gcode end: start_filament_gcode
;_TOOLCHANGE 0
;LAYER_CHANGE
;Z:0.375
;HEIGHT:0.375
G1 Z0.375 F12000
; custom gcode: layer_gcode
M117 Layer 0
; custom gcode end: layer_gcode

G1 E-0.4 F2400
G1 X58.229 Y58.245 F12000
G1 E0 F2400
;TYPE:Skirt
;WIDTH:0.65
G1 F1800
G1 X47.253 Y69.218 E1.22648
G1 X45.475 Y72.072 E1.4922
G1 X45.078 Y74.468 E1.68414
G1 X45.078 Y105.52 E4.13804
G1 X45.839 Y108.793 E4.40362
G1 X47.252 Y110.769 E4.59556
G1 X69.225 Y132.747 E7.05152
G1 X72.078 Y134.524 E7.31719
G1 X74.475 Y134.922 E7.50912
G1 X105.526 Y134.924 E9.96295
G1 X108.8 Y134.163 E10.22859
G1 X110.775 Y132.75 E10.42052
G1 X132.747 Y110.781 E12.87593
G1 X134.524 Y107.928 E13.14157
G1 X134.922 Y105.531 E13.33351
G1 X134.924 Y74.484 E15.78701
G1 X134.163 Y71.211 E16.05259
G1 X132.75 Y69.236 E16.24453
G1 X110.775 Y47.253 E18.70088
G1 X107.921 Y45.474 E18.96663
G1 X105.525 Y45.077 E19.15856
G1 X74.475 Y45.077 E21.61231
G1 X71.202 Y45.838 E21.87787
G1 X69.226 Y47.251 E22.06981
G1 X58.282 Y58.192 E23.29275
G1 X58.685 Y58.595 F12000
G1 F1800
G1 X47.656 Y69.621 E24.52515
G1 X46.045 Y72.169 E24.76341
G1 X45.648 Y74.468 E24.94778
G1 X45.648 Y105.52 E27.40169
G1 X46.31 Y108.46 E27.63981
G1 X47.655 Y110.366 E27.82418
G1 X69.628 Y132.344 E30.28014
G1 X72.176 Y133.955 E30.51835
G1 X74.475 Y134.352 E30.70273
G1 X105.526 Y134.354 E33.15655
G1 X108.466 Y133.692 E33.39473
G1 X110.372 Y132.347 E33.57911
G1 X132.344 Y110.378 E36.03451
G1 X133.955 Y107.83 E36.27269
G1 X134.352 Y105.531 E36.45707
G1 X134.354 Y74.484 E38.91057
G1 X133.692 Y71.545 E39.14869
G1 X132.348 Y69.638 E39.33307
G1 X110.373 Y47.655 E41.78942
G1 X107.824 Y46.044 E42.0277
G1 X105.525 Y45.647 E42.21207
G1 X74.475 Y45.647 E44.66582
G1 X71.536 Y46.309 E44.90393
G1 X69.629 Y47.654 E45.0883
G1 X58.738 Y58.542 E46.30531
G1 X59.141 Y58.945 F12000
G1 F1800
G1 X48.059 Y70.023 E47.54365
G1 X46.614 Y72.27 E47.75474
G1 X46.217 Y74.468 E47.93123
G1 X46.217 Y105.52 E50.38513
G1 X46.784 Y108.129 E50.59609
G1 X48.057 Y109.963 E50.77258
G1 X70.03 Y131.941 E53.22854
G1 X72.277 Y133.386 E53.43959
G1 X74.475 Y133.783 E53.61608
G1 X105.526 Y133.785 E56.0699
G1 X108.135 Y133.218 E56.28092
G1 X109.97 Y131.944 E56.45741
G1 X131.942 Y109.975 E58.91281
G1 X133.386 Y107.729 E59.12383
G1 X133.783 Y105.531 E59.30032
G1 X133.785 Y74.484 E61.75383
G1 X133.218 Y71.876 E61.96479
G1 X131.945 Y70.041 E62.14128
G1 X109.97 Y48.058 E64.59764
G1 X107.723 Y46.613 E64.80874
G1 X105.525 Y46.216 E64.98523
G1 X74.475 Y46.216 E67.43898
G1 X71.866 Y46.783 E67.64993
G1 X70.032 Y48.056 E67.82642
G1 X59.194 Y58.891 E69.03751
M104 S260 ; set temperature
G92 E0
G1 E-0.4 F2400
; printing object First_Layer_Test.stl id:0 copy 0
G1 X74.62 Y52.851 F12000
G1 E0 F2400
;TYPE:External perimeter
;WIDTH:0.7
G1 F1800
G1 X105.38 Y52.851 E2.64424
G1 X127.15 Y74.629 E5.29131
G1 X127.148 Y105.386 E7.9353
G1 X105.381 Y127.15 E10.58134
G1 X74.62 Y127.148 E13.22566
G1 X52.852 Y105.375 E15.87231
G1 X52.852 Y74.613 E18.51672
G1 X74.567 Y52.904 E21.15626
;WIPE_START
G1 X74.973 Y53.205 F12000
;WIPE_END
G92 E0
G1 E-0.4 F2400
G1 X126.964 Y75.092 F12000
G1 E0 F2400
;TYPE:Solid infill
;WIDTH:0.699031
G1 F1800
G1 X105.175 Y53.303 E2.64525
G1 X104.299 Y53.303 E2.72046
G1 X126.698 Y75.702 E5.43972
G1 X126.698 Y76.578 E5.51493
G1 X103.423 Y53.303 E8.34055
G1 X102.547 Y53.303 E8.41576
G1 X126.698 Y77.454 E11.34775
G1 X126.698 Y78.33 E11.42295
G1 X101.671 Y53.303 E14.46129
G1 X100.794 Y53.303 E14.53651
G1 X126.697 Y79.206 E17.6812
G1 X126.697 Y80.082 E17.75641
G1 X99.918 Y53.303 E21.00747
G1 X99.042 Y53.303 E21.08268
G1 X126.697 Y80.959 E24.4401
G1 X126.697 Y81.835 E24.5153
G1 X98.166 Y53.303 E27.97908
G1 X97.29 Y53.303 E28.05429
G1 X126.697 Y82.711 E31.62442
G1 X126.697 Y83.587 E31.69963
G1 X96.414 Y53.303 E35.37612
G1 X95.538 Y53.303 E35.45133
G1 X126.697 Y84.463 E39.23418
G1 X126.697 Y85.339 E39.30939
G1 X94.661 Y53.303 E43.1986
G1 X93.785 Y53.303 E43.27381
G1 X126.697 Y86.215 E47.26938
G1 X126.697 Y87.091 E47.34459
G1 X92.909 Y53.303 E51.44651
G1 X92.033 Y53.303 E51.52173
G1 X126.697 Y87.967 E55.73001
G1 X126.697 Y88.843 E55.80522
G1 X91.157 Y53.303 E60.11986
G1 X90.281 Y53.303 E60.19507
G1 X126.697 Y89.719 E64.61607
G1 X126.697 Y90.595 E64.69128
G1 X89.405 Y53.303 E69.21864
G1 X88.528 Y53.303 E69.29385
G1 X126.697 Y91.471 E73.92757
G1 X126.697 Y92.348 E74.00278
G1 X87.652 Y53.303 E78.74286
G1 X86.776 Y53.303 E78.81807
G1 X126.697 Y93.224 E83.66451
G1 X126.697 Y94.1 E83.73971
G1 X85.9 Y53.303 E88.69251
G1 X85.024 Y53.303 E88.76772
G1 X126.696 Y94.976 E93.82687
G1 X126.696 Y95.852 E93.90208
G1 X84.148 Y53.303 E99.06759
G1 X83.272 Y53.303 E99.1428
G1 X126.696 Y96.728 E104.41467
G1 X126.696 Y97.604 E104.48988
G1 X82.395 Y53.303 E109.86811
G1 X81.519 Y53.303 E109.94332
G1 X126.696 Y98.48 E115.42791
G1 X126.696 Y99.356 E115.50312
G1 X80.643 Y53.303 E121.09406
G1 X79.767 Y53.303 E121.16927
G1 X126.696 Y100.232 E126.86658
G1 X126.696 Y101.108 E126.94179
G1 X78.891 Y53.303 E132.74545
G1 X78.015 Y53.303 E132.82066
G1 X126.696 Y101.984 E138.73068
G1 X126.696 Y102.861 E138.80589
G1 X77.139 Y53.303 E144.82227
G1 X76.262 Y53.303 E144.89748
G1 X126.696 Y103.737 E151.02022
G1 X126.696 Y104.613 E151.09543
G1 X75.386 Y53.303 E157.32453
G1 X74.807 Y53.303 E157.37424
G1 X74.659 Y53.452 E157.39227
G1 X126.551 Y105.344 E163.69208
G1 X126.113 Y105.782 E163.74526
G1 X74.221 Y53.89 E170.04508
G1 X73.782 Y54.328 E170.09826
G1 X125.674 Y106.22 E176.39809
G1 X125.236 Y106.658 E176.45127
G1 X73.344 Y54.766 E182.75109
G1 X72.906 Y55.204 E182.80428
G1 X124.798 Y107.096 E189.1041
G1 X124.36 Y107.534 E189.15729
G1 X72.468 Y55.642 E195.45712
G1 X72.03 Y56.08 E195.5103
G1 X123.922 Y107.972 E201.81014
G1 X123.484 Y108.41 E201.86332
G1 X71.592 Y56.518 E208.16316
G1 X71.154 Y56.956 E208.21634
G1 X123.046 Y108.848 E214.51618
G1 X122.608 Y109.286 E214.56937
G1 X70.716 Y57.394 E220.86921
G1 X70.277 Y57.832 E220.9224
G1 X122.17 Y109.724 E227.22225
G1 X121.732 Y110.162 E227.27543
G1 X69.839 Y58.27 E233.57528
G1 X69.401 Y58.708 E233.62847
G1 X121.293 Y110.6 E239.92832
G1 X120.855 Y111.038 E239.98151
G1 X68.963 Y59.146 E246.28137
G1 X68.525 Y59.584 E246.33455
G1 X120.417 Y111.476 E252.63441
G1 X119.979 Y111.914 E252.6876
G1 X68.087 Y60.022 E258.98747
G1 X67.649 Y60.46 E259.04065
G1 X119.541 Y112.352 E265.34052
G1 X119.103 Y112.79 E265.3937
G1 X67.21 Y60.898 E271.69358
G1 X66.772 Y61.336 E271.74676
G1 X118.665 Y113.228 E278.04664
G1 X118.227 Y113.666 E278.09982
G1 X66.334 Y61.774 E284.39971
G1 X65.896 Y62.212 E284.45289
G1 X117.789 Y114.105 E290.75278
G1 X117.351 Y114.543 E290.80596
G1 X65.458 Y62.65 E297.10585
G1 X65.02 Y63.088 E297.15903
G1 X116.912 Y114.981 E303.45892
G1 X116.474 Y115.419 E303.51211
G1 X64.582 Y63.526 E309.812
G1 X64.144 Y63.964 E309.86519
G1 X116.036 Y115.857 E316.16509
G1 X115.598 Y116.295 E316.21827
G1 X63.705 Y64.402 E322.51818
G1 X63.267 Y64.84 E322.57136
G1 X115.16 Y116.733 E328.87127
G1 X114.722 Y117.171 E328.92445
G1 X62.829 Y65.278 E335.22436
G1 X62.391 Y65.716 E335.27754
G1 X114.284 Y117.609 E341.57746
G1 X113.846 Y118.047 E341.63064
G1 X61.953 Y66.154 E347.93056
G1 X61.515 Y66.592 E347.98374
G1 X113.408 Y118.485 E354.28367
G1 X112.97 Y118.923 E354.33685
G1 X61.077 Y67.03 E360.63678
G1 X60.639 Y67.468 E360.68996
G1 X112.532 Y119.361 E366.98989
G1 X112.093 Y119.799 E367.04307
G1 X60.2 Y67.906 E373.34301
G1 X59.762 Y68.344 E373.39619
G1 X111.655 Y120.237 E379.69613
G1 X111.217 Y120.675 E379.74931
G1 X59.324 Y68.782 E386.04925
G1 X58.886 Y69.22 E386.10243
G1 X110.779 Y121.113 E392.40238
G1 X110.341 Y121.551 E392.45556
G1 X58.448 Y69.658 E398.75551
G1 X58.01 Y70.096 E398.80869
G1 X109.903 Y121.989 E405.10864
G1 X109.465 Y122.427 E405.16183
G1 X57.572 Y70.534 E411.46178
G1 X57.134 Y70.972 E411.51496
G1 X109.027 Y122.865 E417.81492
G1 X108.589 Y123.303 E417.86811
G1 X56.695 Y71.41 E424.16807
G1 X56.257 Y71.848 E424.22125
G1 X108.151 Y123.741 E430.52122
G1 X107.712 Y124.179 E430.5744
G1 X55.819 Y72.286 E436.87437
G1 X55.381 Y72.724 E436.92755
G1 X107.274 Y124.617 E443.22753
G1 X106.836 Y125.056 E443.28071
G1 X54.943 Y73.162 E449.58069
G1 X54.505 Y73.6 E449.63387
G1 X106.398 Y125.494 E455.93385
G1 X105.96 Y125.932 E455.98703
G1 X54.067 Y74.038 E462.28702
G1 X53.628 Y74.476 E462.3402
G1 X105.522 Y126.37 E468.64019
G1 X105.194 Y126.698 E468.68002
G1 X104.974 Y126.698 E468.6989
G1 X53.304 Y75.028 E474.97172
G1 X53.304 Y75.904 E475.04693
G1 X104.098 Y126.698 E481.21338
G1 X103.221 Y126.698 E481.28859
G1 X53.304 Y76.78 E487.34867
G1 X53.304 Y77.657 E487.42388
G1 X102.345 Y126.698 E493.37758
G1 X101.469 Y126.698 E493.4528
G1 X53.304 Y78.533 E499.30013
G1 X53.304 Y79.409 E499.37534
G1 X100.593 Y126.697 E505.11629
G1 X99.717 Y126.697 E505.19151
G1 X53.304 Y80.285 E510.8261
G1 X53.304 Y81.161 E510.90131
G1 X98.84 Y126.697 E516.42952
G1 X97.964 Y126.697 E516.50474
G1 X53.304 Y82.037 E521.92658
G1 X53.304 Y82.913 E522.00179
G1 X97.088 Y126.697 E527.31726
G1 X96.212 Y126.697 E527.39247
G1 X53.304 Y83.789 E532.60157
G1 X53.304 Y84.666 E532.67678
G1 X95.336 Y126.697 E537.7795
G1 X94.46 Y126.697 E537.85472
G1 X53.304 Y85.542 E542.85107
G1 X53.304 Y86.418 E542.92628
G1 X93.583 Y126.697 E547.81626
G1 X92.707 Y126.697 E547.89148
G1 X53.304 Y87.294 E552.67508
G1 X53.304 Y88.17 E552.7503
G1 X91.831 Y126.697 E557.42753
G1 X90.955 Y126.697 E557.50275
G1 X53.304 Y89.046 E562.07361
G1 X53.304 Y89.922 E562.14882
G1 X90.079 Y126.697 E566.61331
G1 X89.202 Y126.697 E566.68853
G1 X53.304 Y90.799 E571.04664
G1 X53.304 Y91.675 E571.12185
G1 X88.326 Y126.697 E575.3736
G1 X87.45 Y126.697 E575.44882
G1 X53.304 Y92.551 E579.59419
G1 X53.304 Y93.427 E579.6694
G1 X86.574 Y126.697 E583.7084
G1 X85.698 Y126.696 E583.78362
G1 X53.304 Y94.303 E587.71625
G1 X53.304 Y95.179 E587.79146
G1 X84.821 Y126.696 E591.61771
G1 X83.945 Y126.696 E591.69293
G1 X53.304 Y96.055 E595.41281
G1 X53.304 Y96.932 E595.48803
G1 X83.069 Y126.696 E599.10154
G1 X82.193 Y126.696 E599.17675
G1 X53.304 Y97.808 E602.68389
G1 X53.304 Y98.684 E602.7591
G1 X81.317 Y126.696 E606.15987
G1 X80.44 Y126.696 E606.23509
G1 X53.304 Y99.56 E609.52948
G1 X53.304 Y100.436 E609.60469
G1 X79.564 Y126.696 E612.79272
G1 X78.688 Y126.696 E612.86793
G1 X53.304 Y101.312 E615.94958
G1 X53.304 Y102.188 E616.02479
G1 X77.812 Y126.696 E619.00007
G1 X76.936 Y126.696 E619.07529
G1 X53.304 Y103.065 E621.94419
G1 X53.304 Y103.941 E622.01941
G1 X76.059 Y126.696 E624.78194
G1 X75.183 Y126.696 E624.85716
G1 X53.038 Y104.55 E627.54566
G92 E0
G1 E-0.4 F2400
; stop printing object First_Layer_Test.stl id:0 copy 0
M107
;TYPE:Custom
; custom gcode: end_filament_gcode
; Filament-specific end gcode 
;END gcode for filament
; custom gcode end: end_filament_gcode
; custom gcode: end_gcode
Print_End
; custom gcode end: end_gcode
; filament used [mm] = 717.74
; filament used [cm3] = 1.73
; total filament used [g] = 0.00
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 5m 2s

; SuperSlicer_config = begin
; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 110
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 100%
; bridge_internal_acceleration = 0
; bridge_internal_fan_speed = -1
; bridge_overlap = 90%
; bridge_overlap_min = 80%
; bridge_speed = 60%
; bridge_speed_internal = 150%
; bridge_type = nozzle
; bridged_infill_margin = 200%
; brim_acceleration = 0
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_separation = 0
; brim_speed = 50%
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; default_speed = 200
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = Print_End
; enforce_full_fill_volume = 1
; enforce_retract_first_layer = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_acceleration = 0
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 105%
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 0.89
; extrusion_spacing = 0
; extrusion_width = 
; fan_always_on = 1
; fan_below_layer_time = 60
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 0
; fan_speedup_time = 0.5
; feature_gcode = 
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 0
; filament_custom_variables = ""
; filament_density = 0
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 0
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = K3
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = ASA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 42%
; fill_pattern = cubic
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 110
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 140%
; first_layer_flow_ratio = 100%
; first_layer_height = 75%
; first_layer_infill_speed = 0
; first_layer_min_speed = 0
; first_layer_size_compensation = 0
; first_layer_size_compensation_layers = 1
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 260
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_point_dist = 200%
; fuzzy_skin_thickness = 150%
; gap_fill_acceleration = 0
; gap_fill_enabled = 1
; gap_fill_flow_match_perimeter = 0%
; gap_fill_last = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 50%
; gcode_comments = 0
; gcode_filename_illegal_char = 
; gcode_flavor = klipper
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; gcode_resolution = 0
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 0.6
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 300%
; init_z_rotate = 0
; interface_shells = 0
; ironing = 0
; ironing_acceleration = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 50%
; ironing_type = top
; layer_gcode = M117 Layer {layer_num}
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 2000,5000
; machine_max_acceleration_extruding = 12500,1250
; machine_max_acceleration_retracting = 12500,1250
; machine_max_acceleration_travel = 20000,1250
; machine_max_acceleration_x = 12500,1000
; machine_max_acceleration_y = 15000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 500,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_gcode_per_second = 1500
; max_layer_height = 0
; max_print_height = 180
; max_print_speed = 80
; max_speed_reduction = 90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 100
; min_layer_height = 0.05
; min_length = 0.015
; min_print_speed = 10
; min_skirt_length = 0
; min_width_top_surface = 100%
; mmu_segmented_region_max_width = 0
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.5
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}.gcode
; over_bridge_flow_ratio = 100%
; overhangs_acceleration = 0
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 55%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 
; perimeter_extrusion_width = 0.46
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 60%
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_custom_variables = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = K3
; print_temperature = 0
; printer_custom_variables = 
; printer_model = 
; printer_notes = 
; printer_settings_id = K3
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; remaining_times_type = m73
; resolution = 0.0125
; resolution_internal = 0.1
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0.4
; retract_length_toolchange = 10
; retract_lift = 0.1
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_first_layer = 0
; retract_lift_top = "Only on top"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_angle_cost = 80%
; seam_gap = 15%
; seam_position = cost
; seam_travel_cost = 20%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_brim = 0
; skirt_distance = 6
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 130%
; skirt_height = 1
; skirts = 3
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 50%
; solid_fill_pattern = rectilineargapfill
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0.48
; solid_infill_overlap = 100%
; solid_infill_speed = 30%
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = print_start EXTRUDER=[first_layer_temperature] BED=[first_layer_bed_temperature] CHAMBER_TARGET=[chamber_temperature]\nG21 ; set units to millimeters\nG90 ; use absolute coordinates\nM82 ; use absolute distances for extrusion\nG92 E0
; start_gcode_manual = 1
; support_material = 0
; support_material_acceleration = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0.2
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_contact_distance_type = filament
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0
; support_material_interface_acceleration = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_fan_speed = -1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 50%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60%
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 260
; template_custom_gcode = 
; thin_perimeters = 80%
; thin_perimeters_all = 20%
; thin_walls = 1
; thin_walls_acceleration = 0
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 100%
; threads = 16
; thumbnails = 48x48,300x300
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_format = PNG
; thumbnails_with_bed = 0
; time_cost = 0
; time_estimation_compensation = 100%
; time_start_gcode = 20
; time_toolchange = 30
; tool_name = ""
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 105%
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 50%
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 1500
; travel_deceleration_use_target = 1
; travel_speed = 200
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_inside_depth = 50%
; wipe_inside_end = 1
; wipe_inside_start = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.005
; SuperSlicer_config = end
